### ISSUE TITLE
when use it in small size, it is constructed

### ISSUE THREAD

**Issue by Devamitta** [digitalpalidictionary/dpd-exporter#7]
When using in small screen (Android or another small screen). Because of “close” button, all tables become small.

![2022-03-28_15-59](https://user-images.githubusercontent.com/39419221/161731280-0824c79d-c08d-4de4-9613-8fe5ed5e0c6e.jpg)

I solved it in my version by just removing this button.

![2022-03-28_16-06](https://user-images.githubusercontent.com/39419221/161731340-2a6ef89b-ed73-4648-9d8f-1c8810ec9a13.jpg)

https://github.com/Devamitta/dps-exporter/tree/SBS

What is the benefit to have this button?

**Comment by bdhrs** [comment]
ok, button is gone. can test it out in the next update.

![2022-04-15_21-04](https://user-images.githubusercontent.com/64521731/163590361-27820be9-f3db-4e59-87df-528fc100a744.png)
