### ISSUE TITLE
icon in Android

### ISSUE THREAD

**Issue by Devamitta** [digitalpalidictionary/dpd-exporter#9]
In Android icon does not appear,

it can be solved by using icon .bmp

Also, the size need to be small, otherwise Android does not index the dictionary.

**Comment by bdhrs** [comment]
![android](https://user-images.githubusercontent.com/64521731/163586930-8da558e9-8bc5-418f-a773-c83590b8dd09.png)

sorted. will be in the next update

**Comment by Devamitta** [comment]
Last DPD update have 2 icons. If get rid of dpd.ico and keep only dpd.bmp it will works in Android, otherwise icon not appear.
![Screenshot_2022-04-22-14-44-26-16_e66e28f718147b6e7216efe19a1092f5.jpg](https://user-images.githubusercontent.com/39419221/164889860-d7500229-4b8d-4d5b-9aa4-3655e8c92c88.jpg)

**Comment by Devamitta** [comment]
I think if you instead of this two lines:
icon_path = dpd_dir.joinpath("favicon/favicon_io nu circle/favicon.ico"),
        icon_bmp_path = dpd_dir.joinpath("favicon/favicon_io nu circle/dpd.bmp")

Will make one line
icon_path = dpd_dir.joinpath("favicon/favicon_io nu circle/dpd.bmp")

It should work on both.
At list in my case the code work for both:
icon_path = Path("./book.bmp")

But as you say it is list important thing in the world, I agree.
